/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

/**
 *
 * @author ichla
 */
public class GUIDepartment extends javax.swing.JFrame {

    /**
     * Creates new form GUIDepartment
     */
    public GUIDepartment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAbrev = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Department");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setText("Abbreviation");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 171, 20));
        getContentPane().add(txtAbrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 80, 20));

        btnDelete.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 70, -1));

        btnSearch.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnSearch.setText("Search");
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, -1));

        btnUpdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        btnInsert.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnInsert.setText("Add");
        btnInsert.setEnabled(false);
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 70, -1));

        btnExit.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnExit.setText("Exit");
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAbrev;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
