/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.PreparaConexao;
import fatec.poo.control.DaoCliente;
import fatec.poo.model.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author ichla
 */
public class GuiCliente extends javax.swing.JFrame {

    /**
     * Creates new form GuiCliente
     */
    public GuiCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCPF = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblLimiteCredito = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtLimiteCredito = new javax.swing.JTextField();
        txtDDD = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        cbxUF = new javax.swing.JComboBox<>();
        lblCEP = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        lblLimiteDisponivel = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblLimite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCPF.setText("CPF");
        getContentPane().add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        lblNome.setText("Nome");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        lblEndereco.setText("Endereco");
        getContentPane().add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        lblTelefone.setText("Telefone");
        getContentPane().add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        lblCidade.setText("Cidade");
        getContentPane().add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        lblLimiteCredito.setText("Limite de crédito");
        getContentPane().add(lblLimiteCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));
        getContentPane().add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 154, -1));

        txtNome.setEnabled(false);
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 350, -1));

        txtEndereco.setEnabled(false);
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 350, -1));

        txtCidade.setEnabled(false);
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 250, -1));

        txtTelefone.setEnabled(false);
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 110, -1));

        txtLimiteCredito.setEnabled(false);
        getContentPane().add(txtLimiteCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 90, -1));

        txtDDD.setEnabled(false);
        getContentPane().add(txtDDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 30, -1));

        lblUF.setText("UF");
        getContentPane().add(lblUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        cbxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        cbxUF.setEnabled(false);
        getContentPane().add(cbxUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 70, -1));

        lblCEP.setText("CEP");
        getContentPane().add(lblCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        txtCEP.setEnabled(false);
        getContentPane().add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 140, -1));

        lblLimiteDisponivel.setText("Limite disponível");
        getContentPane().add(lblLimiteDisponivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, -1, -1));

        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, -1, -1));

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, -1));

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, -1, -1));

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        lblLimite.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 110, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       prepCon = new PreparaConexao("system","Lauri@ellen12");
       prepCon.setDriver("oracle.jdbc.driver.OracleDriver");
       prepCon.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
       daoCliente = new DaoCliente(prepCon.abrirConexao());
       
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        prepCon.fecharConexao();
    }//GEN-LAST:event_formWindowClosed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        cliente = null;
        cliente = daoCliente.consultar(txtCPF.getText());
       
       if (cliente == null){//não encontrou o objeto na BD
           txtCPF.setEnabled(true);
           txtNome.setEnabled(true);
           txtEndereco.setEnabled(true);
           txtCidade.setEnabled(true);
           cbxUF.setEnabled(true);
           txtDDD.setEnabled(true);
           txtTelefone.setEnabled(true);
           txtCEP.setEnabled(true);
           txtLimiteCredito.setEnabled(true);
           lblLimite.setEnabled(true);
           
           txtCPF.requestFocus();
                      
           btnConsultar.setEnabled(false);
           btnIncluir.setEnabled(true);
           btnAlterar.setEnabled(false);
           btnExcluir.setEnabled(false);
       }
       else{ //encontrou o objeto na BD
        
          txtNome.setText(cliente.getNome());
          txtCPF.setText(cliente.getCpf());
          txtEndereco.setText(cliente.getEndereco());
          txtCidade.setText(cliente.getCidade()); 
          cbxUF.setSelectedItem(cliente.getUf());
          txtDDD.setText(cliente.getDdd());
          txtTelefone.setText(cliente.getTelefone());
          txtCEP.setText(cliente.getCep());
          txtLimiteCredito.setText(String.valueOf(cliente.getLimiteCredito()));
          lblLimite.setText(String.valueOf(cliente.getLimiteDisponivel()));
          
           txtCPF.setEnabled(false);
           txtNome.setEnabled(false);
           txtEndereco.setEnabled(true);
           txtCidade.setEnabled(true);
           cbxUF.setEnabled(true);
           txtDDD.setEnabled(true);
           txtTelefone.setEnabled(true);
           txtCEP.setEnabled(true);
           txtLimiteCredito.setEnabled(true);
           lblLimite.setEnabled(false);
                      
           btnConsultar.setEnabled(false);
           btnIncluir.setEnabled(false);
           btnAlterar.setEnabled(true);
           btnExcluir.setEnabled(true);
       }    
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
       cliente = new Cliente(txtNome.getText(), txtCPF.getText(), Double.parseDouble(txtLimiteCredito.getText()));
          
       
       cliente.setEndereco(txtEndereco.getText());
       cliente.setCidade(txtCidade.getText());
       cliente.setUf(cbxUF.getSelectedItem().toString());
       cliente.setDdd(txtDDD.getText());
       cliente.setTelefone(txtTelefone.getText());
       cliente.setCep(txtCEP.getText());
       cliente.setLimiteCredito(Double.parseDouble(txtLimiteCredito.getText()));
       cliente.setLimiteDisponivel(Double.parseDouble(txtLimiteCredito.getText()));
      
       daoCliente.inserir(cliente);
         
       //Incializando a GUI 
       txtCPF.setText(null);
       txtNome.setText(null); 
       txtEndereco.setText(null);
       txtCidade.setText(null);
       cbxUF.setSelectedItem(-1);
       txtDDD.setText(null);
       txtTelefone.setText(null);
       txtCEP.setText(null);
       txtLimiteCredito.setText(null);
       lblLimite.setText(null);
       
       txtCPF.requestFocus();
       
       txtCPF.setEnabled(true);
       txtNome.setEnabled(false);
       txtEndereco.setEnabled(false);
       txtCidade.setEnabled(false);
       cbxUF.setEnabled(false);
       txtDDD.setEnabled(false);
       txtTelefone.setEnabled(false);
       txtCEP.setEnabled(false);
       txtLimiteCredito.setEnabled(false);
       lblLimite.setEnabled(false);
       
       btnConsultar.setEnabled(true);
       btnIncluir.setEnabled(false);
       btnAlterar.setEnabled(false);
       btnExcluir.setEnabled(false);
       
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?")== 0){    //Sim
           cliente.setEndereco(txtEndereco.getText());
           cliente.setCidade(txtCidade.getText());
           cliente.setUf(cbxUF.getSelectedItem().toString());
           cliente.setDdd(txtDDD.getText());
           cliente.setTelefone(txtTelefone.getText());
           cliente.setCep(txtCEP.getText());
           cliente.setLimiteCredito(Double.parseDouble(txtLimiteCredito.getText()));
           cliente.setLimiteDisponivel(Double.parseDouble(lblLimite.getText()));
           
           daoCliente.alterar(cliente);
        }      
        //Incializando a GUI 
        txtCPF.setText(null);
        txtNome.setText(null); 
        txtEndereco.setText(null);
        txtCidade.setText(null);
        cbxUF.setSelectedItem(-1);
        txtDDD.setText(null);
        txtTelefone.setText(null);
        txtCEP.setText(null);
        txtLimiteCredito.setText(null);
        lblLimite.setText(null);
        
        txtCPF.requestFocus();
       
        txtCPF.setEnabled(true);
        txtNome.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtCidade.setEnabled(false);
        cbxUF.setEnabled(false);
        txtDDD.setEnabled(false);
        txtTelefone.setEnabled(false);
        txtCEP.setEnabled(false);
        txtLimiteCredito.setEnabled(false);
        lblLimite.setEnabled(false);
       
        btnConsultar.setEnabled(true);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false); 
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão?") == 0){
                daoCliente.excluir(cliente);

                txtCPF.setText(null);
                txtNome.setText(null); 
                txtEndereco.setText(null);
                txtCidade.setText(null);
                cbxUF.setSelectedItem(-1);
                txtDDD.setText(null);
                txtTelefone.setText(null);
                txtCEP.setText(null);
                txtLimiteCredito.setText(null);
                lblLimite.setText(null);

                txtCPF.requestFocus();

                txtCPF.setEnabled(true);
                txtNome.setEnabled(false);
                txtEndereco.setEnabled(false);
                txtCidade.setEnabled(false);
                cbxUF.setEnabled(false);
                txtDDD.setEnabled(false);
                txtTelefone.setEnabled(false);
                txtCEP.setEnabled(false);
                txtLimiteCredito.setEnabled(false);
                lblLimite.setEnabled(false);

                btnConsultar.setEnabled(true);
                btnIncluir.setEnabled(false);
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false); 
            }    
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxUF;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblLimite;
    private javax.swing.JLabel lblLimiteCredito;
    private javax.swing.JLabel lblLimiteDisponivel;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUF;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtDDD;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtLimiteCredito;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
    private DaoCliente daoCliente;
    private Cliente cliente;
    private PreparaConexao prepCon; 
}
