/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.DaoCliente;
import fatec.poo.control.DaoPedido;
import fatec.poo.control.DaoVendedor;
import fatec.poo.control.PreparaConexao;
import fatec.poo.model.Cliente;
import fatec.poo.model.Pedido;
import fatec.poo.model.Vendedor;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author ichla
 */
public class GuiPedido extends javax.swing.JFrame {

    /**
     * Creates new form GuiPedido
     */
    public GuiPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lblNumPed = new javax.swing.JLabel();
        lblDataPed = new javax.swing.JLabel();
        lblValorPed = new javax.swing.JLabel();
        lblCPFCli = new javax.swing.JLabel();
        lblCPFVend = new javax.swing.JLabel();
        txtNumPed = new javax.swing.JTextField();
        txtDataPed = new javax.swing.JTextField();
        txtValPed = new javax.swing.JTextField();
        txtCPFCli = new javax.swing.JTextField();
        txtCPFVend = new javax.swing.JTextField();
        btnConsultaCPFCli = new javax.swing.JButton();
        btnConsultaCPFVend = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblNomeVendedor = new javax.swing.JLabel();
        lblNomeCliente = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNumPed.setText("Número do pedido");

        lblDataPed.setText("Data do pedido");

        lblValorPed.setText("Valor do Pedido");

        lblCPFCli.setText("CPF do cliente");

        lblCPFVend.setText("CPF do vendedor");

        txtDataPed.setEnabled(false);

        txtValPed.setEnabled(false);

        txtCPFCli.setEnabled(false);

        txtCPFVend.setEnabled(false);

        btnConsultaCPFCli.setText("Consultar");
        btnConsultaCPFCli.setEnabled(false);
        btnConsultaCPFCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaCPFCliActionPerformed(evt);
            }
        });

        btnConsultaCPFVend.setText("Consultar");
        btnConsultaCPFVend.setEnabled(false);
        btnConsultaCPFVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaCPFVendActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblNomeVendedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNomeVendedor.setEnabled(false);

        lblNomeCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNomeCliente.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCPFCli)
                        .addGap(26, 26, 26)
                        .addComponent(txtCPFCli, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultaCPFCli)
                        .addGap(18, 18, 18)
                        .addComponent(lblNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValorPed)
                        .addGap(18, 18, 18)
                        .addComponent(txtValPed, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnConsultar)
                        .addGap(11, 11, 11)
                        .addComponent(btnIncluir)
                        .addGap(9, 9, 9)
                        .addComponent(btnAlterar)
                        .addGap(5, 5, 5)
                        .addComponent(btnExcluir)
                        .addGap(7, 7, 7)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumPed)
                                    .addComponent(lblDataPed))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumPed, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDataPed, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCPFVend)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCPFVend, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultaCPFVend)
                                .addGap(18, 18, 18)
                                .addComponent(lblNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumPed)
                    .addComponent(txtNumPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataPed)
                    .addComponent(txtDataPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorPed)
                    .addComponent(txtValPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCPFCli)
                        .addComponent(txtCPFCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsultaCPFCli))
                    .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCPFVend)
                        .addComponent(txtCPFVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsultaCPFVend))
                    .addComponent(lblNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultar)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
        prepCon = new PreparaConexao("","");
        prepCon.setDriver("oracle.jdbc.driver.OracleDriver");
        prepCon.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        daoPedido = new DaoPedido(prepCon.abrirConexao());
        
        daoCliente = new DaoCliente(prepCon.abrirConexao());
        daoVendedor = new DaoVendedor(prepCon.abrirConexao());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        prepCon.fecharConexao();
    }//GEN-LAST:event_formWindowClosed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        pedido = null;
        pedido = daoPedido.consultar(txtNumPed.getText());
       
       if (pedido == null){//não encontrou o objeto na BD
           txtNumPed.requestFocus();
           txtNumPed.setEnabled(true);
           txtDataPed.setEnabled(true);
           txtValPed.setEnabled(true);
           
           txtCPFCli.setEnabled(true);
           txtCPFVend.setEnabled(false);
           
           btnConsultaCPFCli.setEnabled(true);
           btnConsultaCPFVend.setEnabled(false);
           
           btnConsultar.setEnabled(false);
           btnIncluir.setEnabled(false);
           btnAlterar.setEnabled(false);
           btnExcluir.setEnabled(false); 
       }
       else{ //encontrou o objeto na BD
        
          txtDataPed.setText(pedido.getDataEmissao());
          txtValPed.setText(String.valueOf(pedido.getValorPedido()));
          txtCPFCli.setText(pedido.getCliente().getCpf());
          txtCPFVend.setText(pedido.getVendedor().getCpf());
          lblNomeCliente.setText(pedido.getCliente().getNome());
          lblNomeVendedor.setText(pedido.getVendedor().getNome());
         
          
          txtNumPed.setEnabled(false);
          txtDataPed.setEnabled(true);
          txtValPed.setEnabled(true);
          txtCPFCli.setEnabled(false);
          txtCPFVend.setEnabled(false);

          btnConsultar.setEnabled(false);
          btnIncluir.setEnabled(false);
          btnAlterar.setEnabled(true);
          btnExcluir.setEnabled(true);
          
          btnConsultaCPFCli.setEnabled(false);
          btnConsultaCPFVend.setEnabled(false);
       }    
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        pedido = new Pedido(txtNumPed.getText());
          
        pedido.setDataEmissao(txtDataPed.getText());
        pedido.setValorPedido(Double.parseDouble(txtValPed.getText()));
        
        cliente = daoCliente.consultar(txtCPFCli.getText());
        vendedor = daoVendedor.consultar(txtCPFVend.getText());
        
        pedido.setCliente(cliente);
        cliente.addPedidosCliente(pedido);
        pedido.setVendedor(vendedor);
        vendedor.addPedidoVendedor(pedido);
   
      
        daoPedido.inserir(pedido);
         
        //Incializando a GUI 
        
        txtNumPed.setText(null);
        txtDataPed.setText(null);
        txtValPed.setText(null);
        txtCPFCli.setText(null);
        txtCPFVend.setText(null);
        lblNomeCliente.setText(null);
        lblNomeVendedor.setText(null);
        
        txtNumPed.setEnabled(true);
        txtDataPed.setEnabled(false);
        txtValPed.setEnabled(false);
        txtCPFCli.setEnabled(false);
        txtCPFVend.setEnabled(false);
              
        btnConsultar.setEnabled(true);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?")== 0){//Sim
            cliente = daoCliente.consultar(txtCPFCli.getText());
            vendedor = daoVendedor.consultar(txtCPFVend.getText());
            cliente.retiraPedidosCliente(pedido);
            vendedor.removePedido(pedido);
            
            pedido.setDataEmissao(txtDataPed.getText());
            pedido.setValorPedido(Double.parseDouble(txtValPed.getText()));
            
            cliente.addPedidosCliente(pedido);
            vendedor.addPedidoVendedor(pedido);
            
            daoPedido.alterar(pedido);
        }
        
        txtNumPed.setText(null);
        txtDataPed.setText(null);
        txtValPed.setText(null);
        txtCPFCli.setText(null);
        txtCPFVend.setText(null);
        lblNomeCliente.setText(null);
        lblNomeVendedor.setText(null);
        
        txtNumPed.setEnabled(true);
        txtDataPed.setEnabled(false);
        txtValPed.setEnabled(false);
        txtCPFCli.setEnabled(false);
        txtCPFVend.setEnabled(false);
        
        btnConsultar.setEnabled(true);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        btnConsultaCPFCli.setEnabled(false);
        btnConsultaCPFVend.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão?") == 0){
            cliente = daoCliente.consultar(txtCPFCli.getText());
            vendedor = daoVendedor.consultar(txtCPFVend.getText());
            daoPedido.excluir(pedido); 
            cliente.retiraPedidosCliente(pedido);
            vendedor.removePedido(pedido);
        }
        
        txtNumPed.setText(null);
        txtDataPed.setText(null);
        txtValPed.setText(null);
        txtCPFCli.setText(null);
        txtCPFVend.setText(null);
        lblNomeCliente.setText(null);
        lblNomeVendedor.setText(null);
        
        txtNumPed.setEnabled(true);
        txtDataPed.setEnabled(false);
        txtValPed.setEnabled(false);
        txtCPFCli.setEnabled(false);
        txtCPFVend.setEnabled(false);
        
        btnConsultar.setEnabled(true);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        btnConsultaCPFCli.setEnabled(false);
        btnConsultaCPFVend.setEnabled(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultaCPFCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaCPFCliActionPerformed
        cliente = daoCliente.consultar(txtCPFCli.getText());
        
        if (cliente == null) {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado");
        } else {
            lblNomeCliente.setText(cliente.getNome());
            //txtCPFCli.setEnabled(false);
            //btnConsultaCPFCli.setEnabled(false);

            txtCPFVend.setEnabled(true);
            btnConsultaCPFVend.setEnabled(true);

        }
    }//GEN-LAST:event_btnConsultaCPFCliActionPerformed

    private void btnConsultaCPFVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaCPFVendActionPerformed
        vendedor = daoVendedor.consultar(txtCPFVend.getText());
        
        if (vendedor == null) {
            JOptionPane.showMessageDialog(null, "Vendedor não encontrado");
        } else {
            lblNomeVendedor.setText(vendedor.getNome());
            btnIncluir.setEnabled(true);
        }
    }//GEN-LAST:event_btnConsultaCPFVendActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultaCPFCli;
    private javax.swing.JButton btnConsultaCPFVend;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblCPFCli;
    private javax.swing.JLabel lblCPFVend;
    private javax.swing.JLabel lblDataPed;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeVendedor;
    private javax.swing.JLabel lblNumPed;
    private javax.swing.JLabel lblValorPed;
    private javax.swing.JTextField txtCPFCli;
    private javax.swing.JTextField txtCPFVend;
    private javax.swing.JTextField txtDataPed;
    private javax.swing.JTextField txtNumPed;
    private javax.swing.JTextField txtValPed;
    // End of variables declaration//GEN-END:variables
    DaoPedido daoPedido;
    Pedido pedido;
    PreparaConexao prepCon;
    Cliente cliente;
    Vendedor vendedor;
    DaoCliente daoCliente;
    DaoVendedor daoVendedor;
}
