package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoAluno;
import fatec.poo.model.Aluno;
import javax.swing.JOptionPane;
/**
 *
 * @author ichla
 */
public class Aplic extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public Aplic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRA = new javax.swing.JTextField();
        txtNomeAluno = new javax.swing.JTextField();
        txtP1 = new javax.swing.JTextField();
        txtP2 = new javax.swing.JTextField();
        txtMedia = new javax.swing.JTextField();
        txtSituacao = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("RA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Nome do aluno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 178, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Nota P1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 305, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Nota P2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Média");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Situação");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));
        getContentPane().add(txtRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 170, -1));

        txtNomeAluno.setEnabled(false);
        getContentPane().add(txtNomeAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 178, 170, -1));

        txtP1.setEnabled(false);
        getContentPane().add(txtP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 170, -1));

        txtP2.setEnabled(false);
        getContentPane().add(txtP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 170, -1));
        getContentPane().add(txtMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 95, 42));
        getContentPane().add(txtSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 95, 42));

        btnConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 510, 110, -1));

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 510, 80, -1));

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 510, 80, -1));

        btnInserir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 510, 80, -1));

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 510, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
  
        aluno = null;
        aluno = daoAluno.consultar(Integer.parseInt(txtRA.getText()));
        
        if (aluno == null) {
            txtRA.setEnabled(false);
            txtNomeAluno.setEnabled(true);
            txtP1.setEnabled(true);
            txtP2.setEnabled(true);
            txtNomeAluno.requestFocus();
            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(true);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }else {
            txtNomeAluno.setText(aluno.getNome());
            txtP1.setText(String.valueOf(aluno.getNotaP1()));
            txtP2.setText(String.valueOf(aluno.getNotaP2()));
            txtMedia.setText(String.valueOf(aluno.getMedia()));
            if(aluno.getSituacao()) {
                txtSituacao.setText("Aprovado");
            }else {
                txtSituacao.setText("Reprovado");
            }
            txtRA.setEnabled(false);
            txtNomeAluno.setEnabled(true);
            txtP1.setEnabled(true);
            txtP2.setEnabled(true);
            txtNomeAluno.requestFocus();
            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        aluno = new Aluno(Integer.parseInt(txtRA.getText()), 
                        txtNomeAluno.getText());
        
        aluno.setNotaP1(Double.parseDouble(txtP1.getText()));
        aluno.setNotaP2(Double.parseDouble(txtP2.getText()));
        
        daoAluno.inserir(aluno);
        
        // Inicializando a GUI
        
        txtRA.setText(null);
        txtNomeAluno.setText(null);
        txtP1.setText(null);
        txtP2.setText(null);
        
        txtRA.setEnabled(true);
        txtNomeAluno.setEnabled(false);
        txtP1.setEnabled(false);
        txtP2.setEnabled(false);
        txtRA.requestFocus();
        
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);       
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirmar alteração?")==0) {
            aluno.setNome(txtNomeAluno.getText());
            aluno.setNotaP1(Double.parseDouble(txtP1.getText()));
            aluno.setNotaP2(Double.parseDouble(txtP2.getText()));
            daoAluno.alterar(aluno);
        }
        txtRA.setText(null);
        txtNomeAluno.setText(null);
        txtP1.setText(null);
        txtP2.setText(null);
        txtMedia.setText(null);
        txtSituacao.setText(null);
        txtRA.setEnabled(true); 
        txtNomeAluno.setEnabled(false);
        txtP1.setEnabled(false);
        txtP2.setEnabled(false); 
        txtRA.requestFocus();
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false); 
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirmar exclusão?")==0){
            daoAluno.excluir(aluno);
            
            txtRA.setText(null);
            txtNomeAluno.setText(null);
            txtP1.setText(null);
            txtP2.setText(null);
            txtMedia.setText(null);
            txtSituacao.setText(null);
            txtRA.setEnabled(true); 
            txtNomeAluno.setEnabled(false);
            txtP1.setEnabled(false);
            txtP2.setEnabled(false);
            txtRA.requestFocus();
            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        con = new Conexao("SYSTEM","Lauri@ellen12");
        con.setDriver("oracle.jdbc.driver.OracleDriver");
        con.setConnectionString("jdbc:oracle:thin:@192.166.1.6:1521:xe");
        daoAluno = new DaoAluno(con.abrirConexao());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        con.fecharConexao();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtMedia;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtP1;
    private javax.swing.JTextField txtP2;
    private javax.swing.JTextField txtRA;
    private javax.swing.JTextField txtSituacao;
    // End of variables declaration//GEN-END:variables
    private Aluno aluno;
    private Conexao con;
    private DaoAluno daoAluno;
}   

